# Generated by Django 5.2.6 on 2025-11-13 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veterinarioinfo",
            name="foto_veterinario",
        ),
    ]
