# Generated by Django 5.2.6 on 2025-11-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='consulta_afetada',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Ausencia',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
